services:
  - type: web
    name: medical-bot-api
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: GOOGLE_API_KEY
        sync: false  # Set this in Render dashboard
      - key: PINECONE_API_KEY
        sync: false  # Set this in Render dashboard
      - key: PINECONE_INDEX_NAME
        value: medical-chatbot
      - key: SKIP_DOCUMENT_PROCESSING
        value: true
      - key: LOG_LEVEL
        value: INFO
